# Generated by Django 4.2.27 on 2026-10-07 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_legacy_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_by_email',
            field=models.BooleanField(default=True, help_text='Also send an email for notifications such as a share invitation.'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('share:invited', 'Share invited'), ('share:accepted', 'Share accepted'), ('share:declined', 'Share declined'), ('share:revoked', 'Share revoked'), ('ownership:transferred', 'Ownership transferred')], max_length=32)),
                ('message', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
