# Generated by Django 4.2.30 on 2026-09-29 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_started_parts(apps, schema_editor):
    # "Not started" means no segmentation or transcription work has begun yet
    DocumentPart = apps.get_model("core", "DocumentPart")
    started = DocumentPart.objects.filter(lines__isnull=False).values("pk")
    DocumentPart.objects.filter(pk__in=started).update(editorial_status="in_progress")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0074_instancesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpart",
            name="editorial_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("in_progress", "In progress"),
                    ("transcribed", "Initial transcription complete"),
                    ("reviewed_1", "Reviewed by Editor 1"),
                    ("reviewed_2", "Reviewed by Editor 2"),
                    ("ground_truth", "Ground truth"),
                    ("final", "Final edited copy"),
                    ("ready_for_tei", "Ready for TEI export"),
                ],
                db_index=True,
                default="not_started",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="documentpart",
            name="editorial_status_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentpart",
            name="editorial_status_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(mark_started_parts, migrations.RunPython.noop),
    ]
